/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhasach;

import DTO.NhanVien;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author nguye
 */
public class F_Home extends javax.swing.JFrame {

    /**
     * Creates new form F_Home
     */
    public F_Home() {
        initComponents();
        lb_NhanVien.setText(BienToanCuc.getInstance().getNguoiDangNhap().getTenNhanVien());
    }

    private void resetColor(JPanel p){
        Border border = new LineBorder(new Color(255, 255, 255), 2);
        p.setBorder(border);
    }
    private void setColor(JPanel p){
        Border border = new LineBorder(new Color(34, 117, 239), 2);
        p.setBorder(border);
    }
    public void label_NhanVien(NhanVien nhanVien){
        lb_NhanVien.setText(nhanVien.getTenNhanVien());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_NhanVien = new javax.swing.JLabel();
        lb_ChucVu = new javax.swing.JLabel();
        lb_Logout = new javax.swing.JLabel();
        pn_POS = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pn_QuanLy = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pn_NhapSach = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pn_KhachHang = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pn_NhanVien = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pn_DoiMatKhau = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(39, 117, 239));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("An Nhiên");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Book.png"))); // NOI18N

        lb_NhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lb_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lb_NhanVien.setText("Nguyễn Duy Hải");

        lb_ChucVu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_ChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lb_ChucVu.setText("Nhân viên");

        lb_Logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_login_20px_1.png"))); // NOI18N
        lb_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_NhanVien)
                    .addComponent(lb_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_ChucVu)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pn_POS.setBackground(new java.awt.Color(255, 255, 255));
        pn_POS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_POSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_POSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_POSMouseExited(evt);
            }
        });
        pn_POS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Pos.png"))); // NOI18N
        pn_POS.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(39, 117, 239));
        jLabel10.setText("POS");
        pn_POS.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        pn_QuanLy.setBackground(new java.awt.Color(255, 255, 255));
        pn_QuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_QuanLyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_QuanLyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_QuanLyMouseExited(evt);
            }
        });
        pn_QuanLy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QuanLy.png"))); // NOI18N
        pn_QuanLy.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 117, 239));
        jLabel6.setText("QUẢN LÝ");
        pn_QuanLy.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        pn_NhapSach.setBackground(new java.awt.Color(255, 255, 255));
        pn_NhapSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_NhapSachMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_NhapSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_NhapSachMouseExited(evt);
            }
        });
        pn_NhapSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NhapHang.png"))); // NOI18N
        pn_NhapSach.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(39, 117, 239));
        jLabel14.setText("NHẬP SÁCH");
        pn_NhapSach.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        pn_KhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pn_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_KhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_KhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_KhachHangMouseExited(evt);
            }
        });
        pn_KhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/KhachHang.png"))); // NOI18N
        pn_KhachHang.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(39, 117, 239));
        pn_KhachHang.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(39, 117, 239));
        jLabel24.setText("KHÁCH HÀNG");
        pn_KhachHang.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        pn_NhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pn_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_NhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_NhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_NhanVienMouseExited(evt);
            }
        });
        pn_NhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NhanVien.png"))); // NOI18N
        pn_NhanVien.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(39, 117, 239));
        jLabel21.setText("NHÂN VIÊN");
        pn_NhanVien.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        pn_DoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        pn_DoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_DoiMatKhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_DoiMatKhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_DoiMatKhauMouseExited(evt);
            }
        });
        pn_DoiMatKhau.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(39, 117, 239));
        jLabel18.setText("ĐỔI MẬT KHẨU");
        pn_DoiMatKhau.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/password.png"))); // NOI18N
        pn_DoiMatKhau.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(pn_POS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(pn_NhapSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_DoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(pn_QuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_NhapSach, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_QuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_POS, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_DoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pn_POSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_POSMouseEntered
        setColor(pn_POS);
    }//GEN-LAST:event_pn_POSMouseEntered

    private void pn_POSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_POSMouseExited
        resetColor(pn_POS);
    }//GEN-LAST:event_pn_POSMouseExited

    private void pn_NhapSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_NhapSachMouseEntered
        setColor(pn_NhapSach);
    }//GEN-LAST:event_pn_NhapSachMouseEntered

    private void pn_NhapSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_NhapSachMouseExited
        resetColor(pn_NhapSach);
    }//GEN-LAST:event_pn_NhapSachMouseExited

    private void pn_QuanLyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_QuanLyMouseEntered
        setColor(pn_QuanLy);
    }//GEN-LAST:event_pn_QuanLyMouseEntered

    private void pn_KhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KhachHangMouseEntered
        setColor(pn_KhachHang);
    }//GEN-LAST:event_pn_KhachHangMouseEntered

    private void pn_NhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_NhanVienMouseEntered
        setColor(pn_NhanVien);
    }//GEN-LAST:event_pn_NhanVienMouseEntered

    private void pn_QuanLyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_QuanLyMouseExited
        resetColor(pn_QuanLy);
    }//GEN-LAST:event_pn_QuanLyMouseExited

    private void pn_KhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KhachHangMouseExited
        resetColor(pn_KhachHang);
    }//GEN-LAST:event_pn_KhachHangMouseExited

    private void pn_NhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_NhanVienMouseExited
        resetColor(pn_NhanVien);
    }//GEN-LAST:event_pn_NhanVienMouseExited

    //Click panel
    private void pn_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KhachHangMouseClicked
        BienToanCuc.getInstance().getF_KhachHang().setVisible(true);
    }//GEN-LAST:event_pn_KhachHangMouseClicked

    private void pn_POSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_POSMouseClicked
        BienToanCuc.getInstance().getF_Pos().setVisible(true);
    }//GEN-LAST:event_pn_POSMouseClicked

    private void pn_NhapSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_NhapSachMouseClicked
        BienToanCuc.getInstance().getF_NhapSach().setVisible(true);
    }//GEN-LAST:event_pn_NhapSachMouseClicked

    private void pn_QuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_QuanLyMouseClicked
       BienToanCuc.getInstance().getF_QuanLy().setVisible(true);
    }//GEN-LAST:event_pn_QuanLyMouseClicked

    private void pn_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_NhanVienMouseClicked
       BienToanCuc.getInstance().getF_NhanVien().setVisible(true);
    }//GEN-LAST:event_pn_NhanVienMouseClicked

    private void pn_DoiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DoiMatKhauMouseExited
        resetColor(pn_DoiMatKhau);
    }//GEN-LAST:event_pn_DoiMatKhauMouseExited

    private void pn_DoiMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DoiMatKhauMouseEntered
        setColor(pn_DoiMatKhau);
    }//GEN-LAST:event_pn_DoiMatKhauMouseEntered

    private void pn_DoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DoiMatKhauMouseClicked
        BienToanCuc.getInstance().getF_ThongTinCaNhan().setVisible(true);
    }//GEN-LAST:event_pn_DoiMatKhauMouseClicked

    private void lb_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_LogoutMouseClicked
        BienToanCuc.getInstance().closeF_About();
        BienToanCuc.getInstance().closeF_KhachHang();
        BienToanCuc.getInstance().closeF_NhanVien();
        BienToanCuc.getInstance().closeF_NhapSach();
        BienToanCuc.getInstance().closeF_Pos();
        BienToanCuc.getInstance().closeF_QuanLy();
        BienToanCuc.getInstance().closeF_ThongTinCaNhan();
        BienToanCuc.getInstance().setNguoiDangNhap(null);
        BienToanCuc.getInstance().getF_Login().setVisible(true);
        BienToanCuc.getInstance().closeF_Home();
    }//GEN-LAST:event_lb_LogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_ChucVu;
    private javax.swing.JLabel lb_Logout;
    private javax.swing.JLabel lb_NhanVien;
    private javax.swing.JPanel pn_DoiMatKhau;
    private javax.swing.JPanel pn_KhachHang;
    private javax.swing.JPanel pn_NhanVien;
    private javax.swing.JPanel pn_NhapSach;
    private javax.swing.JPanel pn_POS;
    private javax.swing.JPanel pn_QuanLy;
    // End of variables declaration//GEN-END:variables
}
