/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhasach;

import BLL.BNhaCungCap;
import BLL.BPhieuNhap;
import BLL.BSach;
import DTO.DateBox;
import DTO.NhaCungCap;
import DTO.PhieuNhap;
import DTO.Sach;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class F_NhapSach extends javax.swing.JFrame {

    /**
     * Creates new form F_POS
     */
    public F_NhapSach() {
        initComponents();
        Table_Header_Component(tableView);
        tf_TenNV.setText(BienToanCuc.getInstance().getNguoiDangNhap().getTenNhanVien());
        LoadCB_NhaCCC();
    }
    
    
    public void Table_Header_Component(JTable table){
        table.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD,15));
        table.getTableHeader().setOpaque(false);
    }
    public void LoadCB_NhaCCC(){
        try{
            ArrayList<NhaCungCap> nhaCungCaps = BNhaCungCap.getInstance().getNhaCungCaps();
            cb_TenNCC.addItem(null);
            for (int i = 0; i < nhaCungCaps.size(); i++) {
                cb_TenNCC.addItem(nhaCungCaps.get(i).getTenNhaCC());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
        }
    }
        public ArrayList<Sach> TableToArray() {
        DefaultTableModel mode = (DefaultTableModel) this.tableView.getModel();
        ArrayList<Sach> sachs = new ArrayList<Sach>();
        Vector data = mode.getDataVector();
        data.forEach((t) -> {
            Sach sach = new Sach();
            Vector temp = (Vector) t;
            sach.setMaSach((String) temp.get(0));
            sach.setTenSach((String) temp.get(1));
            sach.setSoLuong((int) temp.get(2));
            sach.setGiaNhap((double) temp.get(3));
            sachs.add(sach);
        });
        return sachs;
    }

    public double TinhTongTien() {
        double tongTien = 0;
        ArrayList<Sach> sachs = TableToArray();
        for (int i = 0; i < sachs.size(); i++) {
            Sach temp = sachs.get(i);
            tongTien = tongTien + temp.getGiaNhap()* temp.getSoLuong();
        }
        return tongTien;
    }

    public int GetIndexMaSachInTable(String maSach) {
        maSach = maSach.toUpperCase();
        ArrayList<Sach> sachs = TableToArray();
        for (int i = 0; i < sachs.size(); i++) {
            Sach temp = sachs.get(i);
            if (temp.getMaSach().equals(maSach)) {
                return i;
            }
        }
        return -1;
    }   
    private void Reset() {
        date_NgayNhap.setDate(new Date());
        cb_TenNCC.setSelectedItem(null);
        lb_ThemSach_ThongBao.setText(null);
        nhaCungCap = null;
        lb_TienHang.setText("0");
        //tf_Bill.setText(null);
        DefaultTableModel mode = (DefaultTableModel) tableView.getModel();
        mode.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date_NgayNhap = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_ThanhToan = new javax.swing.JToggleButton();
        tf_TenNV = new javax.swing.JTextField();
        cb_TenNCC = new javax.swing.JComboBox<>();
        lb_TienHang = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tf_Bill = new javax.swing.JTextArea();
        btn_ThanhToan1 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        tf_MaHangHoa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lb_ThemSach_ThongBao = new javax.swing.JLabel();

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("Mã khách hàng:");

        jTextField9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Tên khách hàng:");

        jTextField10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTextField11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Điện thoại");

        jToggleButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jToggleButton3.setText("Thêm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField10)
                            .addComponent(jTextField11))))
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(31, 31, 31)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhập Sách");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        tableView.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Giá nhập", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableView.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableView.setGridColor(new java.awt.Color(216, 216, 216));
        tableView.setRowHeight(25);
        tableView.setSelectionBackground(new java.awt.Color(23, 130, 209));
        tableView.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableView.setShowGrid(true);
        tableView.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tableViewPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tableView);
        if (tableView.getColumnModel().getColumnCount() > 0) {
            tableView.getColumnModel().getColumn(0).setMinWidth(100);
            tableView.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableView.getColumnModel().getColumn(0).setMaxWidth(100);
            tableView.getColumnModel().getColumn(1).setMinWidth(200);
            tableView.getColumnModel().getColumn(1).setPreferredWidth(200);
            tableView.getColumnModel().getColumn(2).setPreferredWidth(75);
            tableView.getColumnModel().getColumn(3).setMinWidth(100);
            tableView.getColumnModel().getColumn(3).setPreferredWidth(100);
            tableView.getColumnModel().getColumn(3).setMaxWidth(100);
            tableView.getColumnModel().getColumn(4).setMinWidth(100);
            tableView.getColumnModel().getColumn(4).setPreferredWidth(100);
            tableView.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT PHIẾU NHẬP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Ngày nhập");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Nhân viên nhập hàng");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Tiền hàng");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Tên nhà cung cấp");

        btn_ThanhToan.setBackground(new java.awt.Color(34, 177, 239));
        btn_ThanhToan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_ThanhToan.setText("THANH TOÁN (F9)");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        tf_TenNV.setEditable(false);
        tf_TenNV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tf_TenNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_TenNVMouseClicked(evt);
            }
        });
        tf_TenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TenNVActionPerformed(evt);
            }
        });

        cb_TenNCC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_TenNCC.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cb_TenNCCInputMethodTextChanged(evt);
            }
        });
        cb_TenNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TenNCCActionPerformed(evt);
            }
        });
        cb_TenNCC.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_TenNCCPropertyChange(evt);
            }
        });
        cb_TenNCC.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cb_TenNCCVetoableChange(evt);
            }
        });

        lb_TienHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb_TienHang.setForeground(new java.awt.Color(255, 51, 0));
        lb_TienHang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_TienHang.setText("0");
        lb_TienHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lb_TienHang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lb_TienHangPropertyChange(evt);
            }
        });

        tf_Bill.setEditable(false);
        tf_Bill.setColumns(20);
        tf_Bill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tf_Bill.setRows(5);
        jScrollPane3.setViewportView(tf_Bill);

        btn_ThanhToan1.setBackground(new java.awt.Color(34, 177, 239));
        btn_ThanhToan1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_ThanhToan1.setText("TẠO MOI");
        btn_ThanhToan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(date_NgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_TienHang, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_ThanhToan1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_TenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_TenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_TienHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThanhToan1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        lb_TienHang.setHorizontalAlignment(SwingConstants.RIGHT);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Mã Sách");

        tf_MaHangHoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_MaHangHoa.setText("Nhập mã sách");
        tf_MaHangHoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_MaHangHoaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_MaHangHoaFocusLost(evt);
            }
        });
        tf_MaHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_MaHangHoaMouseClicked(evt);
            }
        });
        tf_MaHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MaHangHoaActionPerformed(evt);
            }
        });
        tf_MaHangHoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_MaHangHoaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_MaHangHoaKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Scan");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lb_ThemSach_ThongBao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lb_ThemSach_ThongBao.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ThemSach_ThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_MaHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(654, 654, 654))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(656, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_MaHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_ThemSach_ThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(78, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(573, 573, 573))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_TenNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_TenNVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TenNVMouseClicked

    private void tf_TenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TenNVActionPerformed

    private void cb_TenNCCVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cb_TenNCCVetoableChange

    }//GEN-LAST:event_cb_TenNCCVetoableChange

    private void cb_TenNCCPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_TenNCCPropertyChange

    }//GEN-LAST:event_cb_TenNCCPropertyChange

    private void cb_TenNCCInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cb_TenNCCInputMethodTextChanged

    }//GEN-LAST:event_cb_TenNCCInputMethodTextChanged

    private void cb_TenNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TenNCCActionPerformed
        try{
            if (cb_TenNCC.getSelectedItem() == null)
                nhaCungCap = null;
            else{
                    nhaCungCap = BNhaCungCap.getInstance().getNhaCungCapByTenNCC((String) cb_TenNCC.getSelectedItem());
                    if (!nhaCungCap.getTinhTrang()) {
                        JOptionPane.showMessageDialog(this, "Nhà cung cấp bị ngừng cung cấp");
                        nhaCungCap = null;
                        cb_TenNCC.setSelectedItem(null);
                }
            }
        }catch(Exception e){
            nhaCungCap = null;
            cb_TenNCC.setSelectedItem(null);
            JOptionPane.showMessageDialog(this, "ERROR: " +e.getMessage());
        }
    }//GEN-LAST:event_cb_TenNCCActionPerformed

    private void tf_MaHangHoaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_MaHangHoaFocusGained
        if (tf_MaHangHoa.getText().equals("Nhập mã sách")) {
            tf_MaHangHoa.setText(null);
            tf_MaHangHoa.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf_MaHangHoaFocusGained
    
    private void tf_MaHangHoaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_MaHangHoaFocusLost
        lb_ThemSach_ThongBao.setText(null);
        if (tf_MaHangHoa.getText().trim().length() == 0) {
            tf_MaHangHoa.setText("Nhập mã sách");
            tf_MaHangHoa.setForeground(Color.GRAY);
            return;
        }

        DefaultTableModel mode = (DefaultTableModel) tableView.getModel();
        String maSach = tf_MaHangHoa.getText().trim();
        try{
            Sach sach = BSach.getInstance().getSachByMa(maSach);
            if (sach != null)
                if (sach.getTinhTrang() == true){
                    int index = GetIndexMaSachInTable(tf_MaHangHoa.getText().trim());
                    if (index != -1) {
                        mode.setValueAt((int)mode.getValueAt(index,2) + 1, index, 2);
                        mode.setValueAt((int)mode.getValueAt(index,2) * (double)mode.getValueAt(index,3), index, 4);
                    }
                    else
                        mode.addRow(new Object[]{sach.getMaSach(), sach.getTenSach(), 1, sach.getGiaBan(), 1*sach.getGiaBan()});
                    lb_TienHang.setText(String.valueOf(TinhTongTien()));
                }
                else
                    lb_ThemSach_ThongBao.setText("Sách " + sach.getTenSach() + " đã ngưng nhập");
            else
                lb_ThemSach_ThongBao.setText("Mã sách " + maSach + " không tồn tại");
       }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
        }
        tf_MaHangHoa.setText(null);
        tf_MaHangHoa.requestFocusInWindow();
    }//GEN-LAST:event_tf_MaHangHoaFocusLost

    private void tf_MaHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_MaHangHoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MaHangHoaMouseClicked

    private void tf_MaHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MaHangHoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MaHangHoaActionPerformed

    private void tf_MaHangHoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_MaHangHoaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MaHangHoaKeyPressed

    private void tf_MaHangHoaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_MaHangHoaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MaHangHoaKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lb_TienHangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lb_TienHangPropertyChange

    }//GEN-LAST:event_lb_TienHangPropertyChange

    private void tableViewPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tableViewPropertyChange
        lb_ThemSach_ThongBao.setText(null);
        int index =  tableView.getSelectedRow();
        DefaultTableModel mode = (DefaultTableModel) tableView.getModel();
        
        if (index == -1)
            return;
        else if ((int)mode.getValueAt(index, 2) < 0)
            mode.setValueAt(1, index, 2);
        else if( (int)mode.getValueAt(index, 2) == 0 )
            mode.removeRow(index);
        else{
            mode.setValueAt((int)mode.getValueAt(index, 2), index, 2);
            mode.setValueAt((int)mode.getValueAt(index,2) * (double)mode.getValueAt(index,3), index, 4);
        }
        lb_TienHang.setText(String.valueOf(TinhTongTien()));
    }//GEN-LAST:event_tableViewPropertyChange
    public static String CatTen(String value){
        if (value.length() > 21) {
            value = value.substring(0, 21);
            value = value + "...";
        }
        else{
            for (int i = value.length(); i <= 21; i++)
                value = value + " ";
        }
        return value;
    }
    public void PrintBill(){
        try {
            tf_Bill.setText(null);
            tf_Bill.setText("\n********************************************************************");
            tf_Bill.setText(tf_Bill.getText() + "\n                                           CỬA HÀNG NHÀ SÁCH AN NHIÊN                               ");
            tf_Bill.setText(tf_Bill.getText() + "\n                                                HÓA ĐƠN NHẬP HÀNG                                   ");
            tf_Bill.setText(tf_Bill.getText() + "\n********************************************************************");
            tf_Bill.setText(tf_Bill.getText() + "\nMã phiếu nhập: " + BPhieuNhap.getInstance().getMaPhieuNhapMoiNhat());
            tf_Bill.setText(tf_Bill.getText() + "\t\t\tNgày nhập: " + DateBox.ConvertToString(date_NgayNhap.getDate()));
            tf_Bill.setText(tf_Bill.getText() + "\nTên nhân viên: " + tf_TenNV.getText());
            tf_Bill.setText(tf_Bill.getText() + "\nNhà cung cấp: " + nhaCungCap.getTenNhaCC());
            tf_Bill.setText(tf_Bill.getText() + "\n--------------------------------------------------------------------------------------------");
            tf_Bill.setText(tf_Bill.getText() + "\nMã sách\tTên sách\t\tSố lượng\tĐơn giá\tThành tiền");
            tf_Bill.setText(tf_Bill.getText() + "\n--------------------------------------------------------------------------------------------");
            ArrayList<Sach> sach = TableToArray();
            for (int i = 0; i < sach.size(); i++) {
                tf_Bill.setText(tf_Bill.getText() + "\n" + sach.get(i).getMaSach() + "\t" + CatTen(sach.get(i).getTenSach()) + "\t" + sach.get(i).getSoLuong() + "\t" + sach.get(i).getGiaNhap() + "\t" + sach.get(i).getGiaNhap()*sach.get(i).getSoLuong());
                if (i < sach.size() -1)
                    tf_Bill.setText(tf_Bill.getText() + "\n-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -");
            }                                       
            tf_Bill.setText(tf_Bill.getText() + "\n--------------------------------------------------------------------------------------------");
            tf_Bill.setText(tf_Bill.getText() + "\n"+"\t"+"\t"+"\t"+"\t"+"Tổng tiền: " +"\t"+ lb_TienHang.getText());
            tf_Bill.setText(tf_Bill.getText() + "\n\tCảm ơn và Hẹn gặp lại!");
            
            //tf_Bill.print();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"ERROR: " +  e.getMessage());
        }
    }
    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        String thongBao = "";
        boolean flag = true;
        ArrayList<Sach> sachs = TableToArray();
        
        try {
            if (sachs.isEmpty()) {
                thongBao = thongBao + "\nDanh sách đơn hàng rỗng";
                flag = false;
            }
            if (nhaCungCap == null) {
                thongBao = thongBao + "\nNhà cung cấp không được để trống";
                flag = false;
            }
            else if (!nhaCungCap.getTinhTrang()) {
                thongBao = thongBao + "\nNhà cung cấp đã bị ngừng cung cấp";
                flag = false;
            }
            
            if (flag) {
                    PhieuNhap phieuNhap = new PhieuNhap();
                    phieuNhap.setTenNhanVien(BienToanCuc.getInstance().getNguoiDangNhap().getMaNhanVien());
                    phieuNhap.setTenNhaCungCap(nhaCungCap.getMaNhaCC());
                    phieuNhap.setNgayNhap(date_NgayNhap.getDate());
                    if (BPhieuNhap.getInstance().ThemPhieuNhap(phieuNhap, sachs)) {
                        thongBao = "Thanh toán thành công";
                        PrintBill();
                        Reset();
                    } else {
                        thongBao = "Thanh toán không thành công";
                    }
            }
        }catch (SQLException e) {
            thongBao = "ERROR: " + e.getMessage();
        }
        JOptionPane.showMessageDialog(this, thongBao);
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void btn_ThanhToan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToan1ActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_btn_ThanhToan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_NhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_NhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_NhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_NhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_NhapSach().setVisible(true);
            }
        });
    }
    private NhaCungCap nhaCungCap = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_ThanhToan;
    private javax.swing.JToggleButton btn_ThanhToan1;
    private javax.swing.JComboBox<String> cb_TenNCC;
    private com.toedter.calendar.JDateChooser date_NgayNhap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel lb_ThemSach_ThongBao;
    private javax.swing.JLabel lb_TienHang;
    private javax.swing.JTable tableView;
    private javax.swing.JTextArea tf_Bill;
    private javax.swing.JTextField tf_MaHangHoa;
    private javax.swing.JTextField tf_TenNV;
    // End of variables declaration//GEN-END:variables
}
