/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhasach;



import BLL.BNhanVien;
import BLL.BTaiKhoan;
import DTO.DateBox;
import DTO.NhanVien;
import DTO.TaiKhoan;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class F_NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form F_Pos
     */
    
    public F_NhanVien() {
        initComponents();
        Table_NhanVien_Component();
        Table_TaiKhoan_Component();
        
    }
    
    public void Table_TaiKhoan_Component(){
        Table_Header_Component(tb_TaiKhoan);
        LoadTaiKhoan();
        lb_TK_NhanVien.setText(BienToanCuc.getInstance().getNguoiDangNhap().getTenNhanVien());
    }
    public void Table_NhanVien_Component(){
        Table_Header_Component(tb_NhanVien);
        LoadNhanVien();
        lb_NV_NhanVien.setText(BienToanCuc.getInstance().getNguoiDangNhap().getTenNhanVien());
        date_NV_NgaySinh.setDate(new Date());
    }
    public void Table_Header_Component(JTable table){
        table.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD,15));
        table.getTableHeader().setOpaque(false);
    }
    
    public void ArrayToTableNV(ArrayList<NhanVien> nhanViens){
        if (nhanViens != null) {
            DefaultTableModel mode = (DefaultTableModel)this.tb_NhanVien.getModel();
            mode.setRowCount(0);
            for(NhanVien nv:nhanViens){
                mode.addRow(new Object[]{nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getGioiTinh(), DateBox.ConvertToString(nv.getNgaySinh()),nv.getSoCMND(), nv.getDienThoai(),nv.getTinhTrang()?rb_NV_DangLamViec.getText():rb_NV_NgungLamViec.getText()});
            }
        }
    }
    public void ArrayToTableTK(ArrayList<TaiKhoan> taiKhoans){
        if (taiKhoans != null) {
            DefaultTableModel mode = (DefaultTableModel)this.tb_TaiKhoan.getModel();
            mode.setRowCount(0);
            for(TaiKhoan tk:taiKhoans){
                mode.addRow(new Object[]{tk.getTenDangNhap(),tk.getMaNhanVien(),tk.getTenNhanVien()});
            }
        }
    }
    
    public void LoadTaiKhoan(){
        ArrayList<TaiKhoan> taiKhoans = null;
        try{
            taiKhoans = BTaiKhoan.getInstance().getTaiKhoans();
            ArrayToTableTK(taiKhoans);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi load dữ liệu: " + e.getMessage() );
        }
        
    }
    public void LoadNhanVien(){
        ArrayList<NhanVien> nhanViens = null;
        try{
            nhanViens = BNhanVien.getInstance().getNhanViens();
            ArrayToTableNV(nhanViens);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi load dữ liệu: " + e.getMessage() );
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnGroup_NV_TinhTrang = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_NhanVien = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        tf_NV_Search = new javax.swing.JTextField();
        btn_NV_Search = new javax.swing.JToggleButton();
        lb_NV_NhanVien = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        tf_NV_TenNV = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btn_NhanVien_Them = new javax.swing.JToggleButton();
        rb_NV_Nu = new javax.swing.JRadioButton();
        rb_NV_Nam = new javax.swing.JRadioButton();
        date_NV_NgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        tf_NV_CMND = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tf_NV_DienThoai = new javax.swing.JTextField();
        btn_NV_CapNhap = new javax.swing.JToggleButton();
        jLabel36 = new javax.swing.JLabel();
        rb_NV_DangLamViec = new javax.swing.JRadioButton();
        rb_NV_NgungLamViec = new javax.swing.JRadioButton();
        lb_NV_New = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tb_TaiKhoan = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        tf_TK_Search = new javax.swing.JTextField();
        btn_TK_Search = new javax.swing.JToggleButton();
        lb_TK_NhanVien = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        tf_TK_MaNV = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_TK_TenNV = new javax.swing.JTextField();
        btn_TK_Them = new javax.swing.JToggleButton();
        btn_TK_Xoa = new javax.swing.JToggleButton();
        jLabel37 = new javax.swing.JLabel();
        tf_TK_TenDangNhap = new javax.swing.JTextField();
        lb_TK_New = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        mn_Pos = new javax.swing.JMenu();
        mn_QuanLy = new javax.swing.JMenu();
        mn_KhachHang = new javax.swing.JMenu();
        mn_NhanVien = new javax.swing.JMenu();
        mn_HuongDan = new javax.swing.JMenu();
        mni_About = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhân Viên");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tb_NhanVien.setAutoCreateRowSorter(true);
        tb_NhanVien.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tb_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Giới tính", "Ngày sinh", "Số CMND", "Điện thoại", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_NhanVien.setGridColor(new java.awt.Color(216, 216, 216));
        tb_NhanVien.setRowHeight(25);
        tb_NhanVien.setSelectionBackground(new java.awt.Color(23, 130, 208));
        tb_NhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_NhanVien.setShowGrid(true);
        tb_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_NhanVien);

        jPanel4.setBackground(new java.awt.Color(39, 117, 239));
        jPanel4.setForeground(new java.awt.Color(0, 39, 188));

        tf_NV_Search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tf_NV_Search.setForeground(new java.awt.Color(128, 128, 128));
        tf_NV_Search.setText("Nhập tên hoặc mã nhân viên");
        tf_NV_Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_NV_SearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_NV_SearchFocusLost(evt);
            }
        });
        tf_NV_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_NV_SearchMouseClicked(evt);
            }
        });
        tf_NV_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NV_SearchActionPerformed(evt);
            }
        });

        btn_NV_Search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_NV_Search.setText("Tìm");
        btn_NV_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NV_SearchActionPerformed(evt);
            }
        });

        lb_NV_NhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lb_NV_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lb_NV_NhanVien.setText("Nguyễn Duy Hải");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_NV_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_NV_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(lb_NV_NhanVien)
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_NV_Search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lb_NV_NhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NV_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Tên nhân viên");

        tf_NV_TenNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Ngày sinh");

        btn_NhanVien_Them.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_NhanVien_Them.setText("Thêm");
        btn_NhanVien_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVien_ThemActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_NV_Nu);
        rb_NV_Nu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_NV_Nu.setText("Nữ");

        buttonGroup1.add(rb_NV_Nam);
        rb_NV_Nam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_NV_Nam.setSelected(true);
        rb_NV_Nam.setText("Nam");

        date_NV_NgaySinh.setDate(new java.util.Date(1624875229000L));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setText("Giới tính");

        tf_NV_CMND.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_NV_CMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_NV_CMNDKeyTyped(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel34.setText("Số CMND");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel35.setText("Số điện thoại");

        tf_NV_DienThoai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_NV_DienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_NV_DienThoaiKeyTyped(evt);
            }
        });

        btn_NV_CapNhap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_NV_CapNhap.setText("Cập nhập");
        btn_NV_CapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NV_CapNhapActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel36.setText("Tình trạng");

        btnGroup_NV_TinhTrang.add(rb_NV_DangLamViec);
        rb_NV_DangLamViec.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_NV_DangLamViec.setSelected(true);
        rb_NV_DangLamViec.setText("Đang làm việc");

        btnGroup_NV_TinhTrang.add(rb_NV_NgungLamViec);
        rb_NV_NgungLamViec.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_NV_NgungLamViec.setText("Ngừng làm việc");

        lb_NV_New.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_NV_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_plus_20px.png"))); // NOI18N
        lb_NV_New.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_NV_NewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(tf_NV_DienThoai))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(tf_NV_CMND))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_NV_CapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_NhanVien_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_NV_DangLamViec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(rb_NV_NgungLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_NV_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb_NV_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(date_NV_NgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_NV_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_NV_New, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(tf_NV_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_NV_New, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_NV_Nu)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_NV_Nam)
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_NV_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tf_NV_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_NV_DienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_NV_DangLamViec)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb_NV_NgungLamViec))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_NV_CapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NhanVien_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nhân Viên", jPanel3);

        tb_TaiKhoan.setAutoCreateRowSorter(true);
        tb_TaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tb_TaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên đăng nhập", "Mã nhân viên", "Tên nhân viên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_TaiKhoan.setGridColor(new java.awt.Color(216, 216, 216));
        tb_TaiKhoan.setRowHeight(25);
        tb_TaiKhoan.setSelectionBackground(new java.awt.Color(23, 130, 208));
        tb_TaiKhoan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_TaiKhoan.setShowGrid(true);
        tb_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_TaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tb_TaiKhoan);

        jPanel10.setBackground(new java.awt.Color(39, 117, 239));
        jPanel10.setForeground(new java.awt.Color(0, 39, 188));

        tf_TK_Search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tf_TK_Search.setForeground(new java.awt.Color(128, 128, 128));
        tf_TK_Search.setText("Nhập tên nhân viên, mã nhân viên hoặc tên đăng nhập");
        tf_TK_Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_TK_SearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_TK_SearchFocusLost(evt);
            }
        });
        tf_TK_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_TK_SearchMouseClicked(evt);
            }
        });
        tf_TK_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TK_SearchActionPerformed(evt);
            }
        });

        btn_TK_Search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_TK_Search.setText("Tìm");
        btn_TK_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TK_SearchActionPerformed(evt);
            }
        });

        lb_TK_NhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lb_TK_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lb_TK_NhanVien.setText("Nguyễn Duy Hải");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_TK_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_TK_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addComponent(lb_TK_NhanVien)
                .addGap(38, 38, 38))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lb_TK_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tf_TK_Search, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btn_TK_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Mã nhân viên");

        tf_TK_MaNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_TK_MaNV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_TK_MaNVFocusLost(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Tên nhân viên");

        tf_TK_TenNV.setEditable(false);
        tf_TK_TenNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btn_TK_Them.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_TK_Them.setText("Thêm");
        btn_TK_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TK_ThemActionPerformed(evt);
            }
        });

        btn_TK_Xoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_TK_Xoa.setText("Xoá");
        btn_TK_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TK_XoaActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel37.setText("Tên đăng nhập");

        tf_TK_TenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_TK_TenDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_TK_TenDangNhapKeyTyped(evt);
            }
        });

        lb_TK_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_plus_20px.png"))); // NOI18N
        lb_TK_New.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_TK_NewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(tf_TK_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_TK_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(btn_TK_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_TK_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_TK_TenDangNhap))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_TK_New, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_TK_New, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tf_TK_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(tf_TK_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tf_TK_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TK_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TK_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tài khoản", jPanel2);

        menubar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menubar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        mn_Pos.setText("POS");
        mn_Pos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_PosMouseClicked(evt);
            }
        });
        menubar.add(mn_Pos);

        mn_QuanLy.setText("QUẢN LÝ");
        mn_QuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_QuanLyMouseClicked(evt);
            }
        });
        menubar.add(mn_QuanLy);

        mn_KhachHang.setText("KHÁCH HÀNG");
        mn_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_KhachHangMouseClicked(evt);
            }
        });
        menubar.add(mn_KhachHang);

        mn_NhanVien.setText("NHÂN VIÊN");
        mn_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_NhanVienMouseClicked(evt);
            }
        });
        menubar.add(mn_NhanVien);

        mn_HuongDan.setText("HƯỚNG DẪN");

        mni_About.setText("About");
        mni_About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mni_AboutMouseClicked(evt);
            }
        });
        mni_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_AboutActionPerformed(evt);
            }
        });
        mn_HuongDan.add(mni_About);

        menubar.add(mn_HuongDan);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_TK_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TK_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TK_SearchActionPerformed

    private void tf_TK_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_TK_SearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TK_SearchMouseClicked

    private void tf_NV_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NV_SearchActionPerformed
        
    }//GEN-LAST:event_tf_NV_SearchActionPerformed

    private void tf_NV_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_NV_SearchMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tf_NV_SearchMouseClicked

    private void btn_TK_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TK_XoaActionPerformed
        String thongBao = "";
        try {
            int index = tb_TaiKhoan.getSelectedRow();
            DefaultTableModel mode = (DefaultTableModel) tb_TaiKhoan.getModel();
            if (index == -1)
                return;
            
            if (BTaiKhoan.getInstance().DeteleTaiKhoan((String)mode.getValueAt(index, 0))) {
                thongBao = "Xoá thành công";
                LoadTaiKhoan();
            }
        } catch (SQLException ex) {
            thongBao = "ERROR: " + ex.getMessage();
        }
        JOptionPane.showMessageDialog(this, thongBao);
    }//GEN-LAST:event_btn_TK_XoaActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu1ActionPerformed

    private void btn_TK_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TK_ThemActionPerformed
        String thongBao = "";
        boolean flag = true;
        try{
            if (tf_TK_MaNV.getText().trim().length() == 0){
                thongBao = thongBao + "\nMã nhân viên không được để trống";
                flag = false;
            }
            else if(!(BNhanVien.getInstance().IsExistMaNV(tf_TK_MaNV.getText()))){
                thongBao = thongBao + "\nNhân viên không tồn tại";
                flag = false;
            }
            else if (BTaiKhoan.getInstance().CheckEistsMaNV(tf_TK_MaNV.getText())){
                thongBao = thongBao + "\nNhân viên đã có tài khoản";
                flag = false;
            }
            
            if (tf_TK_TenDangNhap.getText().trim().length() == 0){
                thongBao = thongBao + "\nTên đăng nhập không được để trống";
                flag = false;
            }
            if (BTaiKhoan.getInstance().CheckEistsTenDN(tf_TK_TenDangNhap.getText())){
                thongBao = thongBao + "\nTên đăng nhập đã tồn tại";
                flag = false;
            }
            
            if (flag) {
                TaiKhoan tk = new TaiKhoan();
                tk.setTenDangNhap(tf_TK_TenDangNhap.getText());
                tk.setMaNhanVien(tf_TK_MaNV.getText());

                if (BTaiKhoan.getInstance().ThemTaiKhoan(tk)) {
                    thongBao = thongBao + "Thêm thành công tài khoản cho " + tf_TK_MaNV.getText().trim();
                    LoadTaiKhoan();
                }
            }
        }catch(Exception e){
            thongBao = "Lỗi: " + e.getMessage();
        }
        JOptionPane.showMessageDialog(this, thongBao);
    }//GEN-LAST:event_btn_TK_ThemActionPerformed

    private void tb_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_NhanVienMouseClicked
        // TODO add your handling code here:
        int indexSelectRow = tb_NhanVien.getSelectedRow();
        DefaultTableModel mode = (DefaultTableModel)this.tb_NhanVien.getModel();
            
        tf_NV_TenNV.setText((String)mode.getValueAt(indexSelectRow,1));
        
        //GioiTinh
        if (((String)mode.getValueAt(indexSelectRow,2)).trim().equals(rb_NV_Nam.getText())) 
            rb_NV_Nam.setSelected(true);
        else
            rb_NV_Nu.setSelected(true);
        
        date_NV_NgaySinh.setDate(DateBox.getDate((String)mode.getValueAt(indexSelectRow,3)));
        
        tf_NV_CMND.setText((String)mode.getValueAt(indexSelectRow,4));
        tf_NV_DienThoai.setText((String)mode.getValueAt(indexSelectRow,5));
        
        if (((String)mode.getValueAt(indexSelectRow,6)).trim().equals(rb_NV_DangLamViec.getText())) 
            rb_NV_DangLamViec.setSelected(true);
        else
            rb_NV_NgungLamViec.setSelected(true);
    }//GEN-LAST:event_tb_NhanVienMouseClicked

    private void tb_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_TaiKhoanMouseClicked
        // TODO add your handling code here:
        int indexSelectRow = tb_TaiKhoan.getSelectedRow();
        
        DefaultTableModel mode = (DefaultTableModel)this.tb_TaiKhoan.getModel();
        
        tf_TK_TenDangNhap.setEditable(false);
        tf_TK_MaNV.setEditable(false);
        tf_TK_TenNV.setEditable(false);
        
        tf_TK_TenDangNhap.setText((String)mode.getValueAt(indexSelectRow,0));
        tf_TK_MaNV.setText((String)mode.getValueAt(indexSelectRow,1));
        tf_TK_TenNV.setText((String)mode.getValueAt(indexSelectRow,2));
        
        
    }//GEN-LAST:event_tb_TaiKhoanMouseClicked

    private void lb_TK_NewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_TK_NewMouseClicked
        // TODO add your handling code here:
        tf_TK_TenDangNhap.setEditable(true);
        tf_TK_MaNV.setEditable(true);
        tf_TK_TenNV.setEditable(false);
        
        tf_TK_TenDangNhap.setText(null);
        tf_TK_TenNV.setText(null);
        tf_TK_MaNV.setText(null);
        
        tf_TK_MaNV.requestFocusInWindow();
    }//GEN-LAST:event_lb_TK_NewMouseClicked

    private void lb_NV_NewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_NV_NewMouseClicked
        // TODO add your handling code here:
        tf_NV_TenNV.setText(null);
        rb_NV_Nam.setSelected(true);
        date_NV_NgaySinh.setDate(new Date());
        tf_NV_DienThoai.setText(null);
        tf_NV_CMND.setText(null);
        tf_NV_DienThoai.setText(null);
        rb_NV_DangLamViec.setSelected(true);
        
        tf_NV_TenNV.requestFocusInWindow();
    }//GEN-LAST:event_lb_NV_NewMouseClicked

    private void tf_NV_SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_NV_SearchFocusGained
        if (tf_NV_Search.getText().equals("Nhập tên hoặc mã nhân viên")) {
            tf_NV_Search.setText(null);
            tf_NV_Search.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf_NV_SearchFocusGained

    private void tf_NV_SearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_NV_SearchFocusLost
        if (tf_NV_Search.getText().trim().length() == 0) {
            tf_NV_Search.setText("Nhập tên hoặc mã nhân viên");
            tf_NV_Search.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tf_NV_SearchFocusLost

    private void tf_TK_SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_TK_SearchFocusGained
        if (tf_TK_Search.getText().equals("Nhập tên nhân viên, mã nhân viên hoặc tên đăng nhập")) {
            tf_TK_Search.setText(null);
            tf_TK_Search.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf_TK_SearchFocusGained

    private void tf_TK_SearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_TK_SearchFocusLost
       if (tf_TK_Search.getText().trim().length() == 0) {
            tf_TK_Search.setText("Nhập tên nhân viên, mã nhân viên hoặc tên đăng nhập");
            tf_TK_Search.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tf_TK_SearchFocusLost

    private void btn_TK_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TK_SearchActionPerformed
        try{
            if (tf_TK_Search.getText().trim().length() == 0 || tf_TK_Search.getText().equals("Nhập tên nhân viên, mã nhân viên hoặc tên đăng nhập")){
                LoadTaiKhoan();
                return;
            }
        
            ArrayList<TaiKhoan> taiKhoans = null;
            taiKhoans = BTaiKhoan.getInstance().SearchTaiKhoan(tf_TK_Search.getText().trim());
            ArrayToTableTK(taiKhoans);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage() );
        }
        
    }//GEN-LAST:event_btn_TK_SearchActionPerformed

    private void btn_NV_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NV_SearchActionPerformed
        if (tf_NV_Search.getText().trim().length() == 0 || tf_NV_Search.getText().equals("Nhập tên hoặc mã nhân viên")){
            LoadNhanVien();
            return;
        }
        
        ArrayList<NhanVien> nhanViens = null;
        try{
            nhanViens = BNhanVien.getInstance().searchNV(tf_NV_Search.getText().trim());
            ArrayToTableNV(nhanViens);
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage() );
        }
    }//GEN-LAST:event_btn_NV_SearchActionPerformed

    private void btn_NhanVien_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVien_ThemActionPerformed
        String thongBao = "";
        boolean flag = true;
        try{
            if(tf_NV_TenNV.getText().trim().length() == 0){
                thongBao = thongBao + "\nTên nhân viên không được để trống";
                flag = false;
            }
            if(!(date_NV_NgaySinh.getDate().before(new Date()))){
                thongBao = thongBao + "\nNgày sinh không được lớn hơn ngày hiện tại";
                flag = false;
            }
            if (tf_NV_CMND.getText().trim().length() == 0|| tf_NV_CMND.getText().trim().length() > 13) {
                thongBao = thongBao + "\nSố CMND/CCCD Không được để trống hoặc lớn hơn 13 ký tự";
                flag = false;
            }
            else if(BNhanVien.getInstance().IsExistSoCMND(tf_NV_CMND.getText())){
                thongBao = thongBao + "\nSố CMND/CCCD đã tồn tại";
                flag = false;
            }
            
            if (flag) {
                NhanVien nv = new NhanVien();
                nv.setTenNhanVien(tf_NV_TenNV.getText());
                nv.setGioiTinh(rb_NV_Nam.isSelected()?rb_NV_Nam.getText():rb_NV_Nu.getText());
                nv.setNgaySinh(date_NV_NgaySinh.getDate());
                nv.setSoCMND(tf_NV_CMND.getText());
                nv.setDienThoai(tf_NV_DienThoai.getText());
                nv.setTinhTrang(rb_NV_DangLamViec.isSelected()?true:false);

                if (BNhanVien.getInstance().ThemNhanVien(nv)) {
                      thongBao = thongBao + "\nThêm thành công nhân viên ";
                      LoadNhanVien();
                }
            }
        }catch(Exception e){
            thongBao = "ERROR: " + e.getMessage();
        }
        JOptionPane.showMessageDialog(this, thongBao);
    }//GEN-LAST:event_btn_NhanVien_ThemActionPerformed

    private void tf_TK_MaNVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_TK_MaNVFocusLost
        NhanVien nv = new NhanVien();
        if (!(tf_TK_MaNV.getText().trim().length() == 0)) 
            try {
                nv = BNhanVien.getInstance().getNhanVienByMaNV(tf_TK_MaNV.getText());
                tf_TK_TenNV.setText(nv.getTenNhanVien());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lấy tên nhân viên không thành công");
        }
    }//GEN-LAST:event_tf_TK_MaNVFocusLost

    private void tf_NV_CMNDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_NV_CMNDKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_tf_NV_CMNDKeyTyped

    private void tf_NV_DienThoaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_NV_DienThoaiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_tf_NV_DienThoaiKeyTyped

    private void tf_TK_TenDangNhapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_TK_TenDangNhapKeyTyped
       char c = evt.getKeyChar();
       if (c == ' ')
           evt.consume();
    }//GEN-LAST:event_tf_TK_TenDangNhapKeyTyped
    
    //Menu
    private void mn_PosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_PosMouseClicked
        BienToanCuc.getInstance().getF_Pos().setVisible(true);
    }//GEN-LAST:event_mn_PosMouseClicked

    private void mn_QuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_QuanLyMouseClicked
        BienToanCuc.getInstance().getF_QuanLy().setVisible(true);
    }//GEN-LAST:event_mn_QuanLyMouseClicked

    private void mn_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_KhachHangMouseClicked
        BienToanCuc.getInstance().getF_KhachHang().setVisible(true);
    }//GEN-LAST:event_mn_KhachHangMouseClicked

    private void mn_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_NhanVienMouseClicked
        BienToanCuc.getInstance().getF_NhanVien().setVisible(true);
    }//GEN-LAST:event_mn_NhanVienMouseClicked

    private void mni_AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mni_AboutMouseClicked
        BienToanCuc.getInstance().getF_About().setVisible(true);
    }//GEN-LAST:event_mni_AboutMouseClicked

    private void mni_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_AboutActionPerformed
        BienToanCuc.getInstance().getF_About().setVisible(true);
    }//GEN-LAST:event_mni_AboutActionPerformed

    private void btn_NV_CapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NV_CapNhapActionPerformed
        String thongBao = "";
        boolean flag = true;
        DefaultTableModel mode = (DefaultTableModel) tb_NhanVien.getModel();
        int index = tb_NhanVien.getSelectedRow();
        if (index == -1) {
            return;
        }
        try{
            if(tf_NV_TenNV.getText().trim().length() == 0){
                thongBao = thongBao + "\nTên nhân viên không được để trống";
                flag = false;
            }
            if(!(date_NV_NgaySinh.getDate().before(new Date()))){
                thongBao = thongBao + "\nNgày sinh không được lớn hơn ngày hiện tại";
                flag = false;
            }
            if (tf_NV_CMND.getText().trim().length() == 0|| tf_NV_CMND.getText().trim().length() > 13) {
                thongBao = thongBao + "\nSố CMND/CCCD Không được để trống hoặc lớn hơn 13 ký tự";
                flag = false;
            }
            else {
                NhanVien nv = BNhanVien.getInstance().getNhanVienByCMND(tf_NV_CMND.getText().trim());
                if(nv != null && nv.getMaNhanVien().equals((String)mode.getValueAt(index, 4))){
                thongBao = thongBao + "\nSố CMND/CCCD đã tồn tại";
                flag = false;
                }   
            }
            
            if (flag) {
                NhanVien nv = new NhanVien();
                nv.setMaNhanVien((String)mode.getValueAt(index, 0));
                nv.setTenNhanVien(tf_NV_TenNV.getText());
                nv.setGioiTinh(rb_NV_Nam.isSelected()?rb_NV_Nam.getText():rb_NV_Nu.getText());
                nv.setNgaySinh(date_NV_NgaySinh.getDate());
                nv.setSoCMND(tf_NV_CMND.getText());
                nv.setDienThoai(tf_NV_DienThoai.getText());
                nv.setTinhTrang(rb_NV_DangLamViec.isSelected()?true:false);

                if (BNhanVien.getInstance().UpdateNhanVien(nv)) {
                      thongBao = thongBao + "\nSửa thông tin thành công";
                      LoadNhanVien();
                      LoadTaiKhoan();
                      if (((String)mode.getValueAt(index, 0)).equals(BienToanCuc.getInstance().getNguoiDangNhap().getMaNhanVien())) {
                          BienToanCuc.getInstance().setNguoiDangNhap(BNhanVien.getInstance().getNhanVienByMaNV((String)mode.getValueAt(index, 0)));
                          lb_NV_NhanVien.setText(BienToanCuc.getInstance().getNguoiDangNhap().getTenNhanVien());
                          lb_TK_NhanVien.setText(BienToanCuc.getInstance().getNguoiDangNhap().getTenNhanVien());
                          BienToanCuc.getInstance().getF_Home().label_NhanVien(BienToanCuc.getInstance().getNguoiDangNhap());
                          LoadTaiKhoan();
                      }
                }
                else{
                    thongBao = "Sửa thông tin thành công";
                }
            }
        }catch(Exception e){
            thongBao = "ERROR: " + e.getMessage();
        }
        JOptionPane.showMessageDialog(this, thongBao);
    }//GEN-LAST:event_btn_NV_CapNhapActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new F_NhanVien().setVisible(true);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup_NV_TinhTrang;
    private javax.swing.JToggleButton btn_NV_CapNhap;
    private javax.swing.JToggleButton btn_NV_Search;
    private javax.swing.JToggleButton btn_NhanVien_Them;
    private javax.swing.JToggleButton btn_TK_Search;
    private javax.swing.JToggleButton btn_TK_Them;
    private javax.swing.JToggleButton btn_TK_Xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser date_NV_NgaySinh;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lb_NV_New;
    private javax.swing.JLabel lb_NV_NhanVien;
    private javax.swing.JLabel lb_TK_New;
    private javax.swing.JLabel lb_TK_NhanVien;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenu mn_HuongDan;
    private javax.swing.JMenu mn_KhachHang;
    private javax.swing.JMenu mn_NhanVien;
    private javax.swing.JMenu mn_Pos;
    private javax.swing.JMenu mn_QuanLy;
    private javax.swing.JMenuItem mni_About;
    private javax.swing.JRadioButton rb_NV_DangLamViec;
    private javax.swing.JRadioButton rb_NV_Nam;
    private javax.swing.JRadioButton rb_NV_NgungLamViec;
    private javax.swing.JRadioButton rb_NV_Nu;
    private javax.swing.JTable tb_NhanVien;
    private javax.swing.JTable tb_TaiKhoan;
    private javax.swing.JTextField tf_NV_CMND;
    private javax.swing.JTextField tf_NV_DienThoai;
    private javax.swing.JTextField tf_NV_Search;
    private javax.swing.JTextField tf_NV_TenNV;
    private javax.swing.JTextField tf_TK_MaNV;
    private javax.swing.JTextField tf_TK_Search;
    private javax.swing.JTextField tf_TK_TenDangNhap;
    private javax.swing.JTextField tf_TK_TenNV;
    // End of variables declaration//GEN-END:variables
}
