/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhasach;

import BLL.BTaiKhoan;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class F_ThongTinCaNhan extends javax.swing.JFrame {

    /**
     * Creates new form F_ThongTinCaNhan
     */
    public F_ThongTinCaNhan() {
        initComponents();
        try{
            tf_TenDN.setText(BTaiKhoan.getInstance().getTaiKhoanByMaNV(BienToanCuc.getInstance().getNguoiDangNhap().getMaNhanVien()).getTenDangNhap());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        tf_TenDN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_CapNhap = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_MatKhauCu = new javax.swing.JPasswordField();
        tf_MatKhauMoi = new javax.swing.JPasswordField();
        tf_NhapLai = new javax.swing.JPasswordField();
        lb_ShowPass = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin cá nhân");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("THÔNG TIN CÁ NHÂN");

        tf_TenDN.setEditable(false);
        tf_TenDN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tf_TenDN.setText("001");
        tf_TenDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_TenDNMouseClicked(evt);
            }
        });
        tf_TenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TenDNActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Tên đăng nhập");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Mật khẩu cũ");

        btn_CapNhap.setBackground(new java.awt.Color(255, 255, 255));
        btn_CapNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_CapNhap.setText("Cập nhập");
        btn_CapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhapActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Mật khẩu mới");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Mật khẩu mới");

        tf_MatKhauCu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tf_MatKhauCu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_MatKhauCu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_MatKhauCuKeyTyped(evt);
            }
        });

        tf_MatKhauMoi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tf_MatKhauMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_MatKhauMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_MatKhauMoiKeyTyped(evt);
            }
        });

        tf_NhapLai.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tf_NhapLai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_NhapLaiKeyTyped(evt);
            }
        });

        lb_ShowPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ShowPass.setIcon(new javax.swing.ImageIcon("D:\\OneDrive\\Study Data\\CongNgheJava\\QuanLyNhaSach\\src\\Image\\eye.png")); // NOI18N
        lb_ShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ShowPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_CapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_NhapLai)
                            .addComponent(tf_MatKhauMoi)
                            .addComponent(tf_MatKhauCu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_TenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_ShowPass, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_TenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(lb_ShowPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_MatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_NhapLai, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_CapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhapActionPerformed
        try{
            if (!(tf_MatKhauCu.getText().trim().length() == 0))
                if (!(tf_MatKhauMoi.getText().trim().length() == 0))
                    if ((tf_NhapLai.getText().trim().equals(tf_MatKhauMoi.getText().trim())))
                        if (BTaiKhoan.getInstance().CheckDangNhap(tf_TenDN.getText(), tf_MatKhauCu.getText()))
                            if (BTaiKhoan.getInstance().UpdateTaiKhoan(tf_TenDN.getText(), tf_MatKhauMoi.getText())) {
                                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
                                tf_MatKhauCu.setText(null);
                                tf_MatKhauMoi.setText(null);
                                tf_NhapLai.setText(null);
                                this.dispose();
                            }
                            else
                                JOptionPane.showMessageDialog(this, "Không thành công");
                        else
                            JOptionPane.showMessageDialog(this, "Mật khẩu cũ không đúng");
                    else
                        JOptionPane.showMessageDialog(this, "Mật khẩu mới không khớp");
                else
                    JOptionPane.showMessageDialog(this, "Mật khẩu mới không được để trống");
            else
                JOptionPane.showMessageDialog(this, "Mật khẩu cũ không được để trống");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_CapNhapActionPerformed

    private void tf_MatKhauCuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_MatKhauCuKeyTyped
       char c = evt.getKeyChar();
       if (c == ' ')
           evt.consume();
    }//GEN-LAST:event_tf_MatKhauCuKeyTyped

    private void tf_MatKhauMoiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_MatKhauMoiKeyTyped
        char c = evt.getKeyChar();
        if (c == ' ')
           evt.consume();
    }//GEN-LAST:event_tf_MatKhauMoiKeyTyped

    private void tf_NhapLaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_NhapLaiKeyTyped
        char c = evt.getKeyChar();
       if (c == ' ')
           evt.consume();
    }//GEN-LAST:event_tf_NhapLaiKeyTyped

    private void tf_TenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TenDNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TenDNActionPerformed

    private void tf_TenDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_TenDNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TenDNMouseClicked

    private void lb_ShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ShowPassMouseClicked
        if (tf_MatKhauCu.getEchoChar() != '\u25cf'){
            tf_MatKhauCu.setEchoChar('\u25cf');
            tf_MatKhauMoi.setEchoChar('\u25cf');
            tf_NhapLai.setEchoChar('\u25cf');
            lb_ShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eye.png")));
        }
        else{
            tf_MatKhauCu.setEchoChar((char)0);
            tf_MatKhauMoi.setEchoChar((char)0);
            tf_NhapLai.setEchoChar((char)0);
            lb_ShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_invisible_20px.png")));
        }
    }//GEN-LAST:event_lb_ShowPassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_ThongTinCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_ThongTinCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_ThongTinCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_ThongTinCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getForm().setVisible(true);
            }
        });
    }
    public static F_ThongTinCaNhan getForm() {
        if (f == null) {
            f = new F_ThongTinCaNhan();
            f.setLocationRelativeTo(null);
        }
        return f;
    }
    public static void CloseForm()
    {
        if (f != null) {
            f.dispose();
        }
    }
    private static F_ThongTinCaNhan f;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_CapNhap;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lb_ShowPass;
    private javax.swing.JPasswordField tf_MatKhauCu;
    private javax.swing.JPasswordField tf_MatKhauMoi;
    private javax.swing.JPasswordField tf_NhapLai;
    private javax.swing.JTextField tf_TenDN;
    // End of variables declaration//GEN-END:variables
}
