/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlynhasach;

import BLL.BNhomSach;
import BLL.BSach;
import DTO.NhomSach;
import DTO.Sach;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenHai
 */
public class F_TimSach extends javax.swing.JFrame {

    /**
     * Creates new form F_TimSach
     */
    public F_TimSach() {
        initComponents();
        LoadSach();
        LoadCB_Sach_NhomSach();
        Table_Header_Component(tb_Sach);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        tb_Sach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tf_Sach_TenOrMa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cb_NhomSach = new javax.swing.JComboBox<>();
        btn_Sach_Loc = new javax.swing.JToggleButton();
        btn_Sach_BoLoc = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb_Sach.setAutoCreateRowSorter(true);
        tb_Sach.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tb_Sach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Số lượng", "Giá bán", "Nhóm sách", "Tình Trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Sach.setGridColor(new java.awt.Color(216, 216, 216));
        tb_Sach.setRowHeight(25);
        tb_Sach.setSelectionBackground(new java.awt.Color(23, 130, 208));
        tb_Sach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_Sach.setShowGrid(true);
        tb_Sach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_SachMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tb_Sach);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TÌM KIẾM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Tên hoặc mã sách");

        tf_Sach_TenOrMa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Nhóm sách");

        cb_NhomSach.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btn_Sach_Loc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Sach_Loc.setText("Lọc");
        btn_Sach_Loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sach_LocActionPerformed(evt);
            }
        });

        btn_Sach_BoLoc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Sach_BoLoc.setText("Bỏ lọc");
        btn_Sach_BoLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sach_BoLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Sach_TenOrMa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_NhomSach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_Sach_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                                .addComponent(btn_Sach_BoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Sach_TenOrMa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_NhomSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sach_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sach_BoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ArrayToTableSach(ArrayList<Sach> sachs){
        if (sachs != null) {           
            DefaultTableModel mode = (DefaultTableModel)this.tb_Sach.getModel();
            mode.setRowCount(0);   
            for(Sach s:sachs){     
                mode.addRow(new Object[]{s.getMaSach(), s.getTenSach(), s.getTacGia(), s.getSoLuong(), s.getGiaBan(), s.getNhomHang(),s.getTinhTrang()?"Bình thường":"Ngừng bán"});
            }
        }
    }
    public void LoadCB_Sach_NhomSach(){
        try{
            ArrayList<NhomSach> nhomSachs = null;
            nhomSachs = BNhomSach.getInstance().getNhomSachs();
            if (nhomSachs != null) {
                cb_NhomSach.removeAllItems();
                cb_NhomSach.addItem(null);
                cb_NhomSach.setSelectedItem(null);
                    
                for (NhomSach nhomSach:nhomSachs) {
                    cb_NhomSach.addItem(nhomSach.getTenNhom());
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Lỗi load dữ liệu: " +  ex.getMessage());
        }
    }
    public void LoadSach(){
        try {
            ArrayList<Sach> sachs = null;
            sachs = BSach.getInstance().getSachs();
            ArrayToTableSach(sachs);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi load dữ liệu: " +  ex.getMessage());
        }
    }
    public void Reset(){
        btn_Sach_BoLoc.doClick();
    }
    public void Table_Header_Component(JTable table){
        table.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD,15));
        table.getTableHeader().setOpaque(false);
    }
    private void tb_SachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_SachMouseClicked
        maSach = null;
        int index = tb_Sach.getSelectedRow();
        DefaultTableModel mode = (DefaultTableModel) tb_Sach.getModel();
        maSach = (String) mode.getValueAt(index, 0);
        //BienToanCuc.getInstance().setFlag(true);
        
        if (maSach != null && maSach.length() != 0) {
            F_Pos.lb_TempPosPosChangeValue(maSach);
        }
    }//GEN-LAST:event_tb_SachMouseClicked

    private void btn_Sach_LocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sach_LocActionPerformed
        try{
            ArrayList<Sach> sachs = null;
            sachs = BSach.getInstance().BoLoc(tf_Sach_TenOrMa.getText().trim(),(String)cb_NhomSach.getSelectedItem());
            ArrayToTableSach(sachs);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_Sach_LocActionPerformed

    private void btn_Sach_BoLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sach_BoLocActionPerformed
        tf_Sach_TenOrMa.setText(null);
        cb_NhomSach.setSelectedItem(null);
        LoadSach();
    }//GEN-LAST:event_btn_Sach_BoLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_TimSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_TimSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_TimSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_TimSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_TimSach().setVisible(true);
            }
        });
    }
    private String maSach = null;

    public String getMaSach() {
        return maSach;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_Sach_BoLoc;
    private javax.swing.JToggleButton btn_Sach_Loc;
    private javax.swing.JComboBox<String> cb_NhomSach;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tb_Sach;
    private javax.swing.JTextField tf_Sach_TenOrMa;
    // End of variables declaration//GEN-END:variables
}
